
## Server Properties
server:
  port: 5000

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Dna031011

## Initialize the datasource with available DDL and DML scripts
    initialization-mode: always

## Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update

## The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
## Jackson Properties
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  




